### ISSUE TITLE
[3] CIS Kubernetes Benchmarks v1.24 - Fail Check Fix

### ISSUE THREAD

**Issue by raviranjanelastisys** [elastisys/compliantkubernetes-kubespray#278]
During the workshop , I realized that we have `36` checks fails which can be fixed with some efforts as most of them don't have the risk like changing file permissions etc but yes some investigation needed before applying the fixes.

Maybe it can be useful if we can bring down these number to `0 Fail` to other stakeholders too like Sales,Marketing etc.

![image](https://github.com/elastisys/compliantkubernetes-kubespray/assets/75951259/4a97d519-dc0b-4839-8953-75fc80ab43d5)
 
Documents to follow to fix as it has the remediation too - [CIS Kubernetes 1.24 Benchmark v1.0.0 PDF.pdf](https://github.com/elastisys/compliantkubernetes-kubespray/files/11755356/CIS.Kubernetes.1.24.Benchmark.v1.0.0.PDF.pdf)

List of checks failed: 

- 1.1.9 - Ensure that the Container Network Interface file permissions are set to 600 or more restrictive
- 1.1.10 - Ensure that the Container Network Interface file ownership is set to root:root
- 1.1.12 - Ensure that the etcd data directory ownership is set to etcd:etcd
- 1.1.20 - Ensure that the Kubernetes PKI certificate file permissions are set to 600 or more restrictive
- 1.2.1 - Ensure that the --anonymous-auth argument is set to false
- 1.2.6 - Ensure that the --kubelet-certificate-authority argument is set as appropriate
- 1.2.10 - Ensure that the admission control plugin EventRateLimit is set
- 1.2.18 - Ensure that the --profiling argument is set to false
- 1.2.28 - Ensure that the --client-ca-file argument is set appropriate
- 1.2.29 - Ensure that the --etcd-cafile argument is set as appropriate
- 1.3.6 - Ensure that the RotateKubeletServerCertificate argument is set to true
- 1.4.1 - Ensure that the --profiling argument is set to false
- 4.1.7 - Ensure that the certificate authorities file permissions are set to 600 or more restrictive
- 4.2.1 - Ensure that the --anonymous-auth argument is set to false
- 4.2.2 - Ensure that the --authorization-mode argument is not set to AlwaysAllow
- 4.2.3 - Ensure that the --client-ca-file argument is set as appropriate
- 4.2.4 - Verify that the --read-only-port argument is set to 0
- 4.2.6 - Ensure that the --protect-kernel-defaults argument is set to true
- 4.2.8 - Ensure that the --hostname-override argument is not set
- 4.2.10 - Ensure that the --tls-cert-file and --tls-private-key-file arguments are set as appropriate
- 4.2.11 - Ensure that the --rotate-certificates argument is not set to false
- 4.2.12 - Verify that the RotateKubeletServerCertificate argument is set to true
- 4.2.13 - Ensure that the Kubelet only makes use of Strong Cryptographic Ciphers
- 5.1.6 - Ensure that Service Account Tokens are only mounted where necessary
- 5.2.2 - Minimize the admission of privileged containers
- 5.2.3 - Minimize the admission of containers wishing to share the host process ID namespace
- 5.2.5 - Minimize the admission of containers wishing to share the host network namespace
- 5.2.6 - Minimize the admission of containers with allowPrivilegeEscalation
- 5.2.7 - Minimize the admission of root containers
- 5.2.8 - Minimize the admission of containers with the NET_RAW capability
- 5.2.10 - Minimize the admission of containers with capabilities assigned
- 5.2.12 - Minimize the admission of HostPath volumes
- 5.2.13 - Minimize the admission of containers which use HostPorts
- 5.7.3 - Apply Security Context to Your Pods and Containers
- 5.7.4 - The default namespace should not be used

**Comment by Ajarmar** [comment]
Investigate which of these seem reasonable to fix by referring to the CIS benchmark PDF linked above. If the fix seems simple, just implement it; otherwise, create separate issues for fixing them. Note in investigation document:
- Which failed checks were fixed,
- Which failed checks had separate issues created,
- Which failed checks seem unfeasible for us to fix.

**Comment by viktor-f** [comment]
While doing these. Please look at this [document](https://github.com/elastisys/ck8s-ops/blob/main/docs/release-and-qa/cisbenchmark-qa.md) and add the results of walking through these tests to this [spreadsheet](https://docs.google.com/spreadsheets/d/1m5m2dIAtyUl3RvRlS8n3g82AfXNWuKhd8f1Jjf5nWvY/edit#gid=0).

**Comment by llarsson** [comment]
Great find! Seems like many of them should be very easy to address (file permissions), but the net effect will be positive for the project as a whole!

I think it makes excellent sense to, once we have addressed all the low hanging fruit here, to document on the public docs why some will still fail: everything under Section 5 seems like it will perpetually fail, because they serve as reminders for sticking to best practices, and never possible to just mark as completed. We do have config and safeguards around adhering to them, though, so that's awesome! :tada:
